config/routes.rb
# == Route Map
#

Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'signup', to: 'users/registrations#new', as: :signup
    get 'login', to: 'users/sessions#new', as: :login
    delete 'logout', to: 'users/sessions#destroy', as: :logout
    get 'login_as/:user_id', to: 'users/sessions#login_as'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :objectives do
    member do
      patch :move_up
      patch :move_down
    end
  end

  resources :records, only: %i[index new update]
  resource :user_setting, only: %i[show edit update] do
    post :line_test, on:  :collection
  end
  resources :periods

  root to: 'static_pages#about'
  get '/privacy', to: 'static_pages#privacy'
  get '/term', to: 'static_pages#term'


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def about; end

  def privacy; end

  def term; end
end

app/views/static_pages/about.html.erb
<% content_for :title, 'lean upについて' %>

<div>
  <h2>lean upとは</h2>
  <p>
    lean up の目的は、ダイエットを楽しく継続するサポートをすること。<br>
    ダイエットが続かない要因は、大きく２つ。<br>
    ダイエット自体がストレスになるのと、多様な刺激の中で生活改善のモチベーションを保つのが難しいから。 <br>
    この２つの問題を解決するために、lean upを作っています。<br>
    <br>
    \\ lean upはLINE連携で簡単に会員登録ができます！ //<br>
  </p>
  <div style="display: flex; gap: 20px;">
    <%= button_to '会員登録', signup_path, { method: :get, class: 'ui teal button' } %>
    <%= button_to 'ログイン', login_path, { method: :get, class: 'ui green button' } %>
  </div>
</div>
<div style="margin-top:50px">
  <h2>lean upの使い方</h2>
  <h3>1. ビジョンボードでダイエットの目標を視覚化</h3>
  <div style="display: flex; gap: 20px; flex-wrap: wrap; align-items: center">
    <%= image_tag 'vision_board_preview.png', style: 'width: 200px;' %>
    <p>
      自分が何を目的にダイエットをしているのか、ダイエットの目標を画像や言葉で保存していつでも一覧で確認できます。<br>
      目標を視覚化したものは"ビジョンボード"と呼ばれ、ビジョンボードを日々目にすることは目標達成に有用であると言われています。<br>
      ユーザー設定画面にて、LINE配信機能をONにすれば、LINEにてビジョンボードから登録した画像や文言が毎朝ひとつ配信され、その日いちにち健康的な意思決定ができるようあなたの背中を押します。<br>
    </p>
  </div>

  <h3 style="margin-top: 40px;">2. ストレスなく体重傾向を把握</h3>
  <div style="display: flex; gap: 20px; flex-wrap: wrap; align-items: center">
    <%= image_tag 'records_preview.png', style: 'height: 200px;' %>
    <p>
      体重記録を2週間の移動平均値で表示し、日々の上下の振れ幅を最小化しています。<br>
      もし体重が増えていても、記録完了時にあなたの気持ちを落ち着かせるようなメッセージを表示します。<br>
      生理期間における体重の大幅な増加時は、よりストレスを受けやすいので生理期間特有のメッセージも用意しています。<br>
      （自身の最適な食事バランスと運動量が分かってさえいれば、体重把握は無理にしなくてもいいと思っています。）<br>
    </p>
  </div>
</div>

app/views/static_pages/privacy.html.erb
<% content_for :title, 'プライバシーポリシー' %>

<div class="card card-style">
  <div class="content">
    <p>本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。</p>

    <h2 class="font-18">第1条（個人情報）</h2>
    <p class="mb-2">「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報及び容貌，指紋，声紋にかかるデータ，及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。</p>

    <h2 class="font-18">第2条（個人情報の収集方法）</h2>
    <p class="mb-2">本サービスは，ユーザーが利用登録をする際に氏名，生年月日，住所，電話番号，メールアドレス，銀行口座番号，クレジットカード番号，運転免許証番号などの個人情報をお尋ねすることがあります。また，ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や決済に関する情報を,本サービスの提携先（情報提供元，広告主，広告配信先などを含みます。以下，｢提携先｣といいます。）などから収集することがあります。</p>

    <h2 class="font-18">第3条（個人情報を収集・利用する目的）</h2>
    <p class="mb-2">本サービスが個人情報を収集・利用する目的は，以下のとおりです。</p>
    <ol>
      <li>本サービスの提供・運営のため</li>
      <li>ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）</li>
      <li>ユーザーが利用中のサービスの新機能，更新情報，キャンペーン等のメールを送付するため</li>
      <li>メンテナンス，重要なお知らせなど必要に応じたご連絡のため</li>
      <li>利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの特定をし，ご利用をお断りするため</li>
      <li>ユーザーにご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため</li>
      <li>有料サービスにおいて，ユーザーに利用料金を請求するため</li>
      <li>上記の利用目的に付随する目的</li>
    </ol>

    <h2 class="font-18">第4条（利用目的の変更）</h2>
    <ol>
      <li>本サービスは，利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。</li>
      <li>利用目的の変更を行った場合には，変更後の目的について，本サービス所定の方法により，ユーザーに通知し，または本ウェブサイト上に公表するものとします。</li>
    </ol>

    <h2 class="font-18">第5条（個人情報の第三者提供）</h2>
    <ol>
      <li>本サービスは，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。</li>
      <ol>
        <li>人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき</li>
        <li>公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき</li>
        <li>国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき</li>
        <li>予め次の事項を告知あるいは公表し，かつ本サービスが個人情報保護委員会に届出をしたとき</li>
        <ol>
          <li>利用目的に第三者への提供を含むこと</li>
          <li>第三者に提供されるデータの項目</li>
          <li>第三者への提供の手段または方法</li>
          <li>本人の求めに応じて個人情報の第三者への提供を停止すること</li>
          <li>本人の求めを受け付ける方法</li>
        </ol>
      </ol>
      <li>前項の定めにかかわらず，次に掲げる場合には，当該情報の提供先は第三者に該当しないものとします。</li>
      <ol>
        <li>本サービスが利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合</li>
        <li>合併その他の事由による事業の承継に伴って個人情報が提供される場合</li>
        <li>個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いた場合</li>
      </ol>
    </ol>

    <h2 class="font-18">第6条（個人情報の開示）</h2>
    <ol>
      <li>本サービスは，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。なお，個人情報の開示に際しては，1件あたり1，000円の手数料を申し受けます。</li>
      <ol>
        <li>本人または第三者の生命，身体，財産その他の権利利益を害するおそれがある場合</li>
        <li>本サービスの業務の適正な実施に著しい支障を及ぼすおそれがある場合</li>
        <li>その他法令に違反することとなる場合</li>
      </ol>
      <li>前項の定めにかかわらず，履歴情報および特性情報などの個人情報以外の情報については，原則として開示いたしません。</li>
    </ol>

    <h2 class="font-18">第7条（個人情報の訂正および削除）</h2>
    <ol>
      <li>ユーザーは，本サービスの保有する自己の個人情報が誤った情報である場合には，本サービスが定める手続きにより，本サービスに対して個人情報の訂正，追加または削除（以下，「訂正等」といいます。）を請求することができます。</li>
      <li>本サービスは，ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正等を行うものとします。</li>
      <li>本サービスは，前項の規定に基づき訂正等を行った場合，または訂正等を行わない旨の決定をしたときは遅滞なく，これをユーザーに通知します。</li>
    </ol>

    <h2 class="font-18">第8条（個人情報の利用停止等）</h2>
    <ol>
      <li>本サービスは，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行います。</li>
      <li>前項の調査結果に基づき，その請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の利用停止等を行います。</li>
      <li>本サービスは，前項の規定に基づき利用停止等を行った場合，または利用停止等を行わない旨の決定をしたときは，遅滞なく，これをユーザーに通知します。</li>
      <li> 前2項にかかわらず，利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じるものとします。</li>
    </ol>

    <h2 class="font-18">第9条（プライバシーポリシーの変更）</h2>
    <ol>
      <li>本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。</li>
      <li>本サービスが別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。</li>
    </ol>

    <p class="text-end">以上</p>
  </div>
</div>

app/views/static_pages/term.html.erb
<% content_for :title, '利用規約' %>

<div class="card card-style">
  <div class="content">
    <p>この利用規約（以下，「本規約」といいます。）は，このウェブサイト上で提供するサービス karoyaka（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。</p>

    <h2 class="font-18">第1条（適用）</h2>
    <ol>
      <li>本規約は，ユーザーと当社との間の本サービスの利用に関わる一切の関係に適用されるものとします。</li>
      <li>当社は本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。</li>
      <li>本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。</li>
    </ol>

    <h2 class="font-18">第2条（ユーザーIDおよびパスワードの管理）</h2>
    <ol>
      <li>ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを適切に管理するものとします。</li>
      <li>ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与し，もしくは第三者と共用することはできません。当社は，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。</li>
      <li>ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は，当社に故意又は重大な過失がある場合を除き，当社は一切の責任を負わないものとします。</li>
    </ol>

    <h2 class="font-18">第3条（禁止事項）</h2>
    <p class="mb-2">ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。</p>
    <ol>
      <li>法令または公序良俗に違反する行為</li>
      <li>犯罪行為に関連する行為</li>
      <li>本サービスの内容等，本サービスに含まれる著作権，商標権ほか知的財産権を侵害する行為</li>
      <li>ほかのユーザー，またはその他第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</li>
      <li>本サービスによって得られた情報を商業的に利用する行為</li>
      <li>本サービスの運営を妨害するおそれのある行為</li>
      <li>不正アクセスをし，またはこれを試みる行為</li>
      <li>他のユーザーに関する個人情報等を収集または蓄積する行為</li>
      <li>不正な目的を持って本サービスを利用する行為</li>
      <li>本サービスの他のユーザーまたはその他の第三者に不利益，損害，不快感を与える行為</li>
      <li>他のユーザーに成りすます行為</li>
      <li>本サービスが許諾しない本サービス上での宣伝，広告，勧誘，または営業行為</li>
      <li>面識のない異性との出会いを目的とした行為</li>
      <li>本サービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為</li>
      <li>その他，本サービスが不適切と判断する行為</li>
    </ol>

    <h2 class="font-18">第4条（本サービスの提供の停止等）</h2>
    <ol>
      <li>本サービスは，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。</li>
      <ol>
        <li>本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
        <li>地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合</li>
        <li>コンピュータまたは通信回線等が事故により停止した場合</li>
        <li>その他，当社が本サービスの提供が困難と判断した場合</li>
      </ol>
      <li>本サービスは，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。</li>
    </ol>

    <h2 class="font-18">第5条（利用制限および登録抹消）</h2>
    <ol>
      <li>本サービスは，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，ユーザーに対して，本サービスの全部もしくは一部の利用を制限し，またはユーザーとしての登録を抹消することができるものとします。</li>
      <ol>
        <li>本規約のいずれかの条項に違反した場合</li>
        <li>登録事項に虚偽の事実があることが判明した場合</li>
        <li>本サービスからの連絡に対し，一定期間返答がない場合</li>
        <li>本サービスについて，最終の利用から一定期間利用がない場合</li>
        <li>その他，本サービスの利用を適当でないと判断した場合</li>
      </ol>
      <li>本サービスは，本条に基づき本サービスが行った行為によりユーザーに生じた損害について，一切の責任を負いません。</li>
    </ol>

    <h2 class="font-18">第6条（退会）</h2>
    <p class="mb-3">ユーザーは，当社の定める退会手続により，本サービスから退会できるものとします。</p>

    <h2 class="font-18">第7条（保証の否認および免責事項）</h2>
    <ol>
      <li>本サービスは，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。</li>
      <li>本サービスは，本サービスに起因してユーザーに生じたあらゆる損害について、当社の故意又は重過失による場合を除き、一切の責任を負いません。ただし，本サービスに関するユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。</li>
      <li>本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。</li>
    </ol>

    <h2 class="font-18">第8条（サービス内容の変更等）</h2>
    <p>本サービスは，ユーザーへの事前の告知をもって、本サービスの内容を変更、追加または廃止することがあり、ユーザーはこれを承諾するものとします。</p>

    <h2 class="font-18">第9条（利用規約の変更）</h2>
    <ol>
      <li>本サービスは以下の場合には、ユーザーの個別の同意を要せず、本規約を変更することができるものとします。</li>
      <ol>
        <li>本規約の変更がユーザーの一般の利益に適合するとき。</li>
        <li>本規約の変更が本サービス利用契約の目的に反せず、かつ、変更の必要性、変更後の内容の相当性その他の変更に係る事情に照らして合理的なものであるとき。</li>
      </ol>
      <li>本サービスはユーザーに対し、前項による本規約の変更にあたり、事前に、本規約を変更する旨及び変更後の本規約の内容並びにその効力発生時期を通知します。</li>
    </ol>

    <h2 class="font-18">第10条（個人情報の取扱い）</h2>
    <p class="mb-3">本サービスの利用によって取得する個人情報については，本サービス「プライバシーポリシー」に従い適切に取り扱うものとします。</p>

    <h2 class="font-18">第11条（通知または連絡）</h2>
    <p class="mb-3">ユーザーと本サービスとの間の通知または連絡は，当社の定める方法によって行うものとします。本サービスは,ユーザーから,当社が別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。</p>

    <h2 class="font-18">第12条（権利義務の譲渡の禁止）</h2>
    <p class="mb-3">ユーザーは，本サービスの書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。</p>

    <h2 class="font-18">第13条（準拠法・裁判管轄）</h2>
    <ol>
      <li>本規約の解釈にあたっては，日本法を準拠法とします。</li>
    </ol>

    <p class="text-end">以上</p>
  </div>
</div>