config/routes.rb
# == Route Map
#

Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'signup', to: 'users/registrations#new', as: :signup
    get 'login', to: 'users/sessions#new', as: :login
    delete 'logout', to: 'users/sessions#destroy', as: :logout
    get 'login_as/:user_id', to: 'users/sessions#login_as'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :objectives do
    member do
      patch :move_up
      patch :move_down
    end
  end

  resources :records, only: %i[index new update]
  resource :user_setting, only: %i[show edit update] do
    post :line_test, on:  :collection
  end
  resources :periods

  root to: 'static_pages#about'
  get '/privacy', to: 'static_pages#privacy'
  get '/term', to: 'static_pages#term'


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/objective.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: objectives
#
#  id             :bigint           not null, primary key
#  comment        :text
#  objective_type :integer          not null
#  order          :integer
#  verbal         :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  user_id        :bigint           not null
#
# Indexes
#
#  index_objectives_on_user_id_and_order  (user_id,order)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Objective < ApplicationRecord
  validates :objective_type, presence: true
  validates :images, presence: true, if: :image?
  validate :acceptable_images, if: :image?
  validates :verbal, presence: true, if: :verbal?

  belongs_to :user

  enum :objective_type, { image: 0, verbal: 1 }

  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
    attachable.variant :large, resize_to_limit: [400, 400]
  end

  before_create :set_order

  def acceptable_images
    return unless images.attached?

    acceptable_types = %w[image/jpeg image/png image/gif image/webp]
    images.each do |image|
      errors.add(:images, :invalid_type) unless image.content_type.in?(acceptable_types)
    end
  end

  def move_up!
    return if order == user.objectives.maximum(:order)

    Objective.transaction do
      upper_objective = user.objectives.find_by(order: order + 1)
      return unless upper_objective

      current_order = order.to_i # オブジェクトの参照から数値の参照に
      update!(order: current_order + 1)
      upper_objective.update!(order: current_order)
    end
  end

  def move_down!
    return if order.zero?

    Objective.transaction do
      lower_objective = user.objectives.find_by(order: order - 1)
      return unless lower_objective

      current_order = order.to_i
      update!(order: current_order - 1)
      lower_objective.update!(order: current_order)
    end
  end

  private

  def set_order
    self.order = user.objectives.count
  end
end

app/controllers/objectives_controller.rb
# frozen_string_literal: true

class ObjectivesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_objective, only: %i[show edit update destroy]

  def index
    @objectives = current_user.objectives.order(order: :desc)
    @maximum = @objectives.maximum(:order)
  end

  def show; end

  def new
    @objective = Objective.new(objective_type: :image)
  end

  def edit; end

  def create
    @objective = Objective.new(objective_params)
    if @objective.save
      redirect_to @objective, notice: t('objective.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @objective.update(objective_params)
      redirect_to @objective, notice: t('objective.updated')
    else
      render 'edit'
    end
  end

  def destroy
    @objective.destroy
    redirect_to objectives_path, notice: t('objective.destroyed')
  end

  def move_up
    @objective = current_user.objectives.find(params[:id])
    @objective.move_up!
    redirect_to objectives_path, notice: t('objective.moved_up')
  end

  def move_down
    @objective = current_user.objectives.find(params[:id])
    @objective.move_down!
    redirect_to objectives_path, notice: t('objective.moved_down')
  end

  private

  def set_objective
    @objective = current_user.objectives.find(params[:id])
  end

  def objective_params
    params.expect(objective: [:objective_type, :verbal, :comment, :order,
                              { images: [] }]).merge(user_id: current_user.id)
  end
end

app/views/objectives/_form.html.erb
<div data-controller="form">
  <%= form_with(model: objective, class: "ui form #{objective.errors.any? ? 'error' : ''}", data: { turbo: false }) do |form| %>
    <% if objective.errors.any? %>
      <div class="ui error message">
        <ul class="list">
          <% objective.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="inline fields">
      <label for="objective_objective_type">タイプ：</label>
      <div class="field">
        <div class="ui radio checkbox">
          <%= form.radio_button :objective_type, :image, { class: 'hidden', data: { form_target: 'select' ,action: 'form#toggleVisibility'} } %>
          <%= form.label :objective_type_image, "画像" %>
        </div>
      </div>
      <div class="field">
        <div class="ui radio checkbox">
          <%= form.radio_button :objective_type, :verbal, { class: 'hidden', data: { form_target: 'select' ,action: 'form#toggleVisibility'} } %>
          <%= form.label :objective_type_verbal, "言葉" %>
        </div>
      </div>
    </div>

    <div class="field" data-form-target="verbal">
      <%= form.label :verbal, '言葉' %>
      <%= form.text_field :verbal, placeholder: '理想の姿の自分は何を感じている？ 気分が上がる言葉は？', data: { form_target: 'verbalInput' } %>
    </div>

    <div data-form-target="image">
      <div class="field">
        <%= render 'image', { form:, objective: } %>
      </div>

      <div class="field">
        <%= form.label :comment, 'メモ' %>
        <%= form.text_area :comment, placeholder: '理想のイメージについて補足メモ', data: { form_target: 'imageInput' } %>
      </div>
    </div>

    <div class="ui hidden divider"></div>

    <%= form.submit "送信", class: "ui teal submit button" %>
  <% end %>
</div>

app/views/objectives/_image.html.erb
<div data-controller="image">
    <%= form.label :images, '理想のイメージ' %>
    <%= form.file_field :images, multiple: true, style: 'margin-bottom: 10px;', data: { form_target: 'imageInput', action: 'change->image#preview'} %>

    <div data-image-target="previewArea" style="display: flex; align-items: stretch; flex-wrap: wrap; gap: 10px;">
        <%# area for preview images %>
    </div>

    <p style="margin: 10px 0 5px;">↓ 保存済み画像 ↓</p>
    <% if objective.images.attached? %>
        <div style="display: flex; align-items: stretch; flex-wrap: wrap; gap: 10px;">
        <% objective.images.select(&:persisted?).each do |image| %>
            <div style="display: flex; flex-direction: column; align-items: center; justify-content: space-between; gap: 5px;" data-image-target="wrapper">
                <%= image_tag image.variant(:thumb), data: { image_target: 'image' } %>
                <%= form.hidden_field :images, multiple: true, value: image.signed_id %>
                <%= button_tag '削除', type: 'button', data: { image_target: 'detachButton', action: 'click->image#deleteImage' }, class: 'mini ui basic button' %>
            </div>
        <% end %>
        </div>
    <% end %>
</div>

app/views/objectives/_objective.html.erb
<div style="text-align: center;">
  <div>
    <p>タイプ：<%= objective.verbal? ? '言葉' : '画像' %></p>
  </div>
  <div class="ui hidden divider"></div>
  <% if objective.verbal? %>
    <div style="min-height: 50px;">
        <p><%= objective.verbal %></p>
    </div>
  <% end %>
  <% if objective.image? %>
    <div>
      <% if objective.images %>
        <% objective.images.each do |image| %>
          <%= image_tag image.variant(:large) %>
        <% end %>
      <% end %>
    </div>
    <% if objective.comment.present? %>
      <div>
        <p>メモ：<%= objective.comment %></p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/objectives/_objective_item.html.erb
<div class="ui centered card" id="objective_<%= objective.id %>">
  <% if objective.image? %>
    <div class="image">
      <%= image_tag objective.images.first.variant(:large) %>
    </div>
    <div class="content">
      <div class="meta"><%= objective.comment %></div>
      <%= render partial: 'order_icons', locals: { objective:, objectives:, maximum: } %>
    </div>
  <% end %>
  <% if objective.verbal? %>
    <div class="content">
      <div class="description"><%= objective.verbal %></div>
      <%= render partial: 'order_icons', locals: { objective:, objectives:, maximum: } %>
    </div>
  <% end %>
  <%= link_to objective, class: 'ui bottom attached button', style: 'color: inherit;' do %>
    <i class="edit icon"></i>
    詳細
  <% end %>
</div>

app/views/objectives/_order_icons.html.erb
<div class="right aligned" style="margin-top:10px" id="order_icons">
  <%= button_to move_up_objective_path(objective), disabled: objective.order == maximum, method: :patch do %>
    <i class="angle up icon <%= 'disabled' if objective.order == maximum %>"></i>
  <% end %>
  <%= button_to move_down_objective_path(objective), disabled: objective.order.zero?, method: :patch do %>
    <i class="angle down icon <%= 'disabled' if objective.order.zero? %>"></i>
  <% end %>
  <i class="thumbs up outline icon"></i>
</div>

app/views/objectives/edit.html.erb
<h1>edit vision board</h1>

<%= render "form", objective: @objective %>

<div class="ui hidden divider"></div>

<div class="ui horizontal segments">
    <%= link_to @objective, class: 'ui segment' do %>
      <i class="undo icon"></i>
      編集をキャンセル
    <% end %>
    <%= link_to objectives_path, class: 'ui segment' do %>
      <i class="list ui icon"></i>
      一覧に戻る
    <% end %>
</div>

app/views/objectives/index.html.erb
<% turbo_refreshes_with(method: :morph, scroll: :preserve) %>
<div class="ui two column centered grid">
  <div class="column ui center aligned">
    <h1>vision board</h1>
    <%= link_to new_objective_path do %>
      <button class="fluid ui teal basic button"><i class="add icon"></i>追加する</button>
    <% end %>
  </div>
</div>
<div class="ui hidden divider"></div>
<p style="text-align: center;color: #999">ビジョンボードをLINEで配信!!<br>（by 設定画面にてLINE連携 & 配信許可 & 配信アカウントを友達追加）</p>
<div id="objectives">
  <% @objectives.each do |objective| %>
    <%= render partial: 'objective_item', locals: { objective:, objectives: @objectives, maximum: @maximum } %>
  <% end %>
</div>

app/views/objectives/new.html.erb
<h1>add to vision board</h1>

<%= render "form", objective: @objective %>

<div class="ui hidden divider"></div>

<div class="ui horizontal segments">
  <%= link_to objectives_path, class: 'ui segment center aligned' do %>
    <i class="list ui icon"></i>
    一覧に戻る
  <% end %>
</div>

app/views/objectives/show.html.erb
<div class="ui center aligned grid one column">
  <h1 class="column">vision board detail</h1>

  <div class="column">
    <%= render @objective %>
  </div>

  <div class="ui horizontal segments">
    <%= link_to edit_objective_path(@objective), class: 'ui segment' do %>
      <i class="edit icon"></i>
      編集
    <% end %>
    <%= link_to objectives_path, class: 'ui segment' do %>
      <i class="list ui icon"></i>
      一覧へ
    <% end %>
    <%= link_to @objective, class: 'ui segment', data: { turbo_method: :delete, turbo_confirm: '削除しますか？' } do %>
      <i class="trash alternate icon"></i>
      削除
    <% end %>
  </div>
</div>