config/routes.rb
# == Route Map
#

Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'signup', to: 'users/registrations#new', as: :signup
    get 'login', to: 'users/sessions#new', as: :login
    delete 'logout', to: 'users/sessions#destroy', as: :logout
    get 'login_as/:user_id', to: 'users/sessions#login_as'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :objectives do
    member do
      patch :move_up
      patch :move_down
    end
  end

  resources :records, only: %i[index new update]
  resource :user_setting, only: %i[show edit update] do
    post :line_test, on:  :collection
  end
  resources :periods

  root to: 'static_pages#about'
  get '/privacy', to: 'static_pages#privacy'
  get '/term', to: 'static_pages#term'


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/_footer_menu.html.erb
<div class="ui borderless bottom fixed labeled icon menu three item grey">
  <%= link_to objectives_path, class: "item #{'active' if current_page?(objectives_path) || current_page?(root_path)}" do %>
    <i class="compass icon"></i>vision board
  <% end %>
  <%= link_to records_path, class: "item #{'active' if current_page?(records_path)}" do %>
    <i class="map icon"></i>weight
  <% end %>
  <%= link_to user_setting_path, class: "item #{'active' if current_page?(user_setting_path)}" do %>
    <i class="cogs icon"></i>setting
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Lean Up" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%= favicon_link_tag 'favicon.ico' %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <div class="ui two column centered grid" style="margin-top: 10px;">
     <div class="column" style="min-width:300px;">
       <div id='flashes'></div>
       <% if notice %>
         <div class="ui positive message notice">
           <i class="check icon"></i>
           <span><%= notice %></span>
         </div>
       <% end %>
       <% if alert %>
         <div class="ui negative message alert">
           <i class="exclamation triangle icon"></i>
           <span><%= alert %></span>
         </div>
       <% end %>
       <div style="margin-top: 30px; margin-bottom: 100px;">
        <%= yield %>
       </div>
     </div>
   </div>
   <%= render partial: 'layouts/footer_menu' %>
  </body>
</html>